export const bettingSites = [
  {
    id: 1,
    name: "Midnite",
    logo: "/mid.svg",
    rating: 4.7,
    claimed: 26103,
    bonus: "Bet €10 Get €20 + 50 Free Spins",
    features: ["Esports Focus", "Modern Interface", "Fast Withdrawals"],
    cta: "💸 Claim Bonus",
    disclaimer: "18+ | GambleAware.org | T&C Apply",
    livebetting: true,
    cashOut: true,
    irishSupport: true,
    betBuilder: true,
    esports: true,
    loyalty: true,
  },
  {
    id: 2,
    name: "Spreadex Sports",
    logo: "/spread.png",
    rating: 4.8,
    claimed: 27876,
    bonus: "Join & get €60 in Free Bets",
    features: ["Spread Betting", "Fixed Odds", "Sports Focus"],
    cta: "💸 Claim Bonus",
    disclaimer: "18+ | GambleAware.org | T&C Apply",
    livebetting: true,
    cashOut: true,
    irishSupport: true,
    betBuilder: true,
    esports: true,
    loyalty: true,
  },
  {
    id: 3,
    name: "Mr.Play",
    logo: "/mrplay.png",
    rating: 4.7,
    claimed: 185120,
    bonus: "Bet €5 Get €10",
    features: ["Casino & Sports", "Irish Market", "Simple UX"],
    cta: "💸 Claim Bonus",
    disclaimer: "18+ | GambleAware.org | T&C Apply",
    livebetting: true,
    cashOut: true,
    irishSupport: true,
    betBuilder: true,
    esports: false,
    loyalty: true,
  },
  {
    id: 4,
    name: "BetFred",
    logo: "/betfred.png",
    rating: 4.9,
    claimed: 265457,
    bonus: "Bet €10 → Get €50",
    features: ["Fast Payouts", "Best Odds", "Live Streaming"],
    cta: "💸 Claim Bonus",
    disclaimer: "18+ | GambleAware.org | T&C Apply",
    livebetting: true,
    cashOut: true,
    irishSupport: true,
    betBuilder: true,
    esports: false,
    loyalty: true,
  },
  {
    id: 5,
    name: "BoyleSports",
    logo: "/boyle.png",
    rating: 4.9,
    claimed: 29105,
    bonus: "Bet €10 Get €30 + €10 Casino Bonus",
    features: ["Irish Owned", "GAA Specials", "Local Support"],
    cta: "💸 Claim Bonus",
    disclaimer: "18+ | GambleAware.org | T&C Apply",
    livebetting: true,
    cashOut: true,
    irishSupport: true,
    betBuilder: true,
    esports: false,
    loyalty: true,
  },
  {
    id: 6,
    name: "BetVictor",
    logo: "/betvictor.png",
    rating: 4.9,
    claimed: 29891,
    bonus: "Bet €10 → Get €30 in Free Bets",
    features: ["Competitive Odds", "Cash Out", "Bet Builder"],
    cta: "💸 Claim Bonus",
    disclaimer: "18+ | GambleAware.org | T&C Apply",
    livebetting: true,
    cashOut: true,
    irishSupport: true,
    betBuilder: true,
    esports: false,
    loyalty: true,
  },
]

export const testingSteps = [
  {
    title: "License & Security Check",
    description: "Verify Irish licensing and security protocols",
  },
  {
    title: "Payment Speed Test",
    description: "Test withdrawal and deposit processing times",
  },
  {
    title: "Odds Quality Test",
    description: "Compare odds across major sporting events",
  },
  {
    title: "UX & Mobile UX Review",
    description: "Evaluate user experience on all devices",
  },
  {
    title: "Bonus Verification",
    description: "Verify bonus terms and claiming process",
  },
  {
    title: "Responsible Gambling Review",
    description: "Check responsible gambling tools and support",
  },
]
